#!/bin/bash
# Cathedral Lab — Live Leaderboard
#
# Shows evolution progress across all generations.
# Updates Obsidian vault with a MOC page.
#
# Usage:
#   ./leaderboard.sh          # Terminal dashboard
#   ./leaderboard.sh --obsidian  # Also write to Obsidian vault

set +e

LAB_DIR="$(cd "$(dirname "$0")" && pwd)"
DISTILL_DIR="$LAB_DIR/distilled"
GEN_DIR="$LAB_DIR/generations"
OBSIDIAN_VAULT="$HOME/Documents/Cathedral Ops"
WRITE_OBSIDIAN=false
[ "$1" = "--obsidian" ] && WRITE_OBSIDIAN=true

# ── Terminal Dashboard ────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║         CATHEDRAL LAB — EVOLUTION LEADERBOARD        ║"
echo "╠══════════════════════════════════════════════════════╣"

# Count generations
GEN_COUNT=$(ls -d "$GEN_DIR"/gen-* 2>/dev/null | wc -l | tr -d ' ')
TASK_COUNT=$(ls -d "$LAB_DIR"/tasks/*/ 2>/dev/null | wc -l | tr -d ' ')
SKILL_COUNT=$(ls "$DISTILL_DIR"/skill-*.md 2>/dev/null | wc -l | tr -d ' ')

printf "║  Generations: %-39s ║\n" "$GEN_COUNT"
printf "║  Benchmark Tasks: %-34s ║\n" "$TASK_COUNT"
printf "║  Skills Distilled: %-33s ║\n" "$SKILL_COUNT"

# Model oracle status
if [ -f "$LAB_DIR/model-registry.json" ]; then
    MODEL_COUNT=$(python3 -c "import json; print(len(json.load(open('$LAB_DIR/model-registry.json')).get('models',[])))" 2>/dev/null)
    ORACLE_DATE=$(python3 -c "import json; print(json.load(open('$LAB_DIR/model-registry.json')).get('updated','unknown')[:16])" 2>/dev/null)
    printf "║  Models: %-12s  Oracle: %-22s ║\n" "$MODEL_COUNT" "$ORACLE_DATE"
fi

echo "╠══════════════════════════════════════════════════════╣"
echo "║  LATEST WINNER                                       ║"

if [ -f "$DISTILL_DIR/LATEST_WINNER.json" ]; then
    python3 -c "
import json
w = json.load(open('$DISTILL_DIR/LATEST_WINNER.json'))
p = w.get('patterns', {})
print(f'║  Source: {w[\"source\"]:45s} ║')
print(f'║  Score:  {w[\"best_score\"]:<45.4f} ║')
print(f'║  Style:  {p.get(\"orchestration_style\",\"unknown\"):45s} ║')
print(f'║  Tools:  {p.get(\"tool_count\",0):<45d} ║')
" 2>/dev/null
else
    echo "║  No winners yet — run the lab first!                 ║"
fi

echo "╠══════════════════════════════════════════════════════╣"
echo "║  MODEL ROUTING (Oracle)                              ║"

if [ -f "$LAB_DIR/model-registry.json" ]; then
    python3 -c "
import json
r = json.load(open('$LAB_DIR/model-registry.json'))
for task, model in r.get('routing', {}).items():
    # Find benchmark speed
    speed = ''
    for m in r.get('models', []):
        if m['name'] == model and 'benchmark' in m:
            speed = f\" ({m['benchmark']['tokens_per_sec']} t/s)\"
    print(f'║  {task:15s} → {model:20s}{speed:10s}    ║')
" 2>/dev/null
fi

echo "╠══════════════════════════════════════════════════════╣"
echo "║  RECENT GENERATIONS                                  ║"

# Show last 5 generations
if [ -d "$GEN_DIR" ]; then
    for gen in $(ls -td "$GEN_DIR"/gen-* 2>/dev/null | head -5); do
        gen_name=$(basename "$gen")
        variant_count=$(ls -d "$gen"/*/ 2>/dev/null | wc -l | tr -d ' ')
        printf "║  %-20s  %s variants            ║\n" "$gen_name" "$variant_count"
    done
else
    echo "║  No generations yet                                  ║"
fi

echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ── Lab loop status ───────────────────────────────────────
echo "Lab Loop Status:"
if tmux has-session -t cathedral-lab 2>/dev/null; then
    echo "  RUNNING in tmux session 'cathedral-lab'"
else
    ACTIVE_LABS=$(tmux list-sessions 2>/dev/null | grep -c "lab-" || echo 0)
    if [ "$ACTIVE_LABS" -gt 0 ]; then
        echo "  RUNNING: $ACTIVE_LABS active lab sessions"
        tmux list-sessions 2>/dev/null | grep "lab-" | sed 's/^/    /'
    else
        echo "  STOPPED — start with: cd cathedral-lab && ./lab-loop.sh 100x"
    fi
fi

# ── Obsidian output ───────────────────────────────────────
if $WRITE_OBSIDIAN && [ -d "$OBSIDIAN_VAULT" ]; then
    PAGE="$OBSIDIAN_VAULT/Cathedral Lab Leaderboard.md"

    python3 -c "
import json
from datetime import datetime

distill_dir = '$DISTILL_DIR'
lab_dir = '$LAB_DIR'

# Load data
winner = {}
try:
    winner = json.load(open(f'{distill_dir}/LATEST_WINNER.json'))
except: pass

registry = {}
try:
    registry = json.load(open(f'{lab_dir}/model-registry.json'))
except: pass

page = f'''---
tags: [cathedral-lab, auto-generated]
updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
---

# Cathedral Lab Leaderboard

> Auto-generated by \`leaderboard.sh\`. Do not edit manually.

## Current Winner

| Metric | Value |
|--------|-------|
| Source | {winner.get('source', 'none')} |
| Score | {winner.get('best_score', 0):.4f} |
| Style | {winner.get('patterns', {}).get('orchestration_style', 'unknown')} |
| Tools | {winner.get('patterns', {}).get('tool_count', 0)} |
| Timestamp | {winner.get('timestamp', 'unknown')} |

## Model Oracle Routing

| Task | Model | Speed |
|------|-------|-------|
'''

for task, model in registry.get('routing', {}).items():
    speed = ''
    for m in registry.get('models', []):
        if m['name'] == model and 'benchmark' in m:
            speed = f\"{m['benchmark']['tokens_per_sec']} t/s\"
    page += f'| {task} | {model} | {speed} |\\n'

page += '''
## Links

- [[Cathedral Ops]] — Main operations hub
- [[ATHAME]] — Research lab node
- [[FURNACE]] — Production node
'''

print(page)
" > "$PAGE" 2>/dev/null

    echo ""
    echo "Obsidian page updated: $PAGE"
fi
